#!/usr/bin/python
# -*- coding:UTF-8 -*-

import os
import argparse
import sys 

binPaths = os.path.split(os.path.realpath(__file__))
libPath = os.path.realpath(binPaths[0]+'/../lib')
sys.path.append(libPath)
import MongoDB 
import Utils
import json

def usage():
    pname = os.path.basename(__file__)
    print(pname + " --output_path <output_path> --data_json <data_json>")
    exit(1)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--output_path', default='', help='前置插件或步骤output输出路径')
    parser.add_argument('--data_json', default='', help='JSON数据文件')
    args = parser.parse_args()

    output_path = args.output_path
    data_json = args.data_json
    if (data_json == None or data_json == '') and (output_path == None or output_path == '' ) :
        usage()

    plugin_data = None
    Util = Utils.Utils()
    if data_json != None and data_json != '' :
        data_json = Util.handleJsonstr(data_json)
        plugin_data = json.loads(data_json, strict=False)
    else :
        plugin_data = Util.getOutput(output_path)

    #valid = Util.isJson(plugin_data)
    #if valid == False :
    #    print("Illegal parameter :{} / {}".format(output_path,data_json))
    #    exit(-1)
    if plugin_data == None : 
        print("please check plugin input param data format : {}".format(data_json))
    else :
        plugin_type = plugin_data['type']
        collect_data = plugin_data['data']
        #print("type : {} , data : {}".format(plugin_type , collect_data))
        if collect_data == None or len(collect_data) == 0 :
            print("exec warn: plug execution has no data.")
            exit(0)
        
        for entity in collect_data:
            table = entity['table']
            uniqueName = entity['uniqueName']
            data = entity['data']
            #新增统一的采集更新时间
            data['_updatetime'] = Util.getCurrentTime()
            db = MongoDB.MongoDB()
            #保存采集的数据
            unique_query = {}
            unique_query['$and'] = uniqueName
            count = db.count(table ,unique_query)
            if count == 0 : 
                db.insert(table,data)
            else :
                db.update(table ,unique_query , data)
            db.close()
        


    
