#!/usr/bin/perl
use strict;
use FindBin;
use File::Basename;
use Cwd 'abs_path';
use Getopt::Long;

use SSHRemoteExec;
use DeployUtils;
use ServerAdapter;

Getopt::Long::Configure("pass_through");

sub usage {
    my $pname = basename($0);

    print("Usage: $pname [--verbose 0|1] [--envpath EnvPath]\n");
    print("              [--supass SuPassword] [--eofstr EOFString] [--failstr FailString]\n");
    print("              [--timeout TimeoutSecs] [-o SSHOptions] cmd\n");
    print("\n");
    print("       --envpath:   Env path in the data directory, example:ATM/ATMP/PRD\n");
    print("       --node:      Host node json\n");
    print("       --supass:    su execute user password\n");
    print("       --eofstr:    when command outpute match eofstr, the execute will be terminated\n");
    print("       --failstr:   when command outpute match failstr, the execute will be terminated and return faled\n");
    print("       --timeout:   tiemout for ssh execute\n");
    print("       --o:         ssh options, example: \"SendEnv EXEC_PASSWORD;ForwardX11 yes\"\n");
    print("       cmd:         command text\n");

    exit(1);
}

sub main {
    my ( $isHelp, $isVerbose, $envPath, $version );
    my ( $node, $supass, $sshOpts, $cmd, $eofStr, $failStr, $timeOut );

    $isVerbose = 0;

    $cmd = '';

    sub addCmd {
        my $item = shift(@_);
        $cmd = $cmd . ' ' . $item;
    }

    GetOptions(
        'h|help'         => \$isHelp,
        'v|verbose=i'    => \$isVerbose,
        'envpath=s{0,1}' => \$envPath,
        'node=s'         => \$node,
        'supass=s'       => \$supass,
        'eofstr=s'       => \$eofStr,
        'failstr=s'      => \$failStr,
        'timeout=i'      => \$timeOut,
        'o=s'            => \$sshOpts,
        '<>'             => \&addCmd
    );

    usage() if ( defined($isHelp) );

    my $optionError = 0;
    my $nodeInfo    = {};
    if ( not defined($node) ) {
        $node = $ENV{AUTOEXEC_NODE};
    }

    if ( not defined($node) or $node eq '' ) {
        $optionError = 1;
    }
    else {
        $nodeInfo = from_json($node);
    }

    if ( $cmd eq '' ) {
        $optionError = 1;
        print("ERROR: must instance path with optoin --inspath.\n");
    }

    if ( $optionError == 1 ) {
        usage();
    }

    my $hasError = 0;

    if ( defined($eofStr) and $eofStr =~ /^\{([\w-\d]+)\}/ ) {
        $eofStr =~ s/^\{[\w-\d]+\}//;
        $eofStr = Encode::encode( lc($1), Encode::decode( 'utf-8', $eofStr ) );
    }

    my $hasOptError = 0;

    my $host    = $nodeInfo->{host};
    my $port    = $nodeInfo->{protocolPort};
    my $user    = $nodeInfo->{username};
    my $pass    = $nodeInfo->{password};
    my $insId   = $nodeInfo->{resourceId};
    my $insName = $nodeInfo->{nodeName};

    my $sshExec = new SSHRemoteExec( $host, $port, $user, $pass, $isVerbose, $cmd, undef, $eofStr, $failStr, $supass, $timeOut, $sshOpts );
    my $ret = $sshExec->exec();

    $hasError = $hasError + $ret;

    if ( $sshExec->{status} eq 'SUCCESS' ) {
        print("FINEST: ssh remote exec success.\n");
    }
    elsif ( $sshExec->{status} eq 'WARN' ) {
        print("WARN: ssh remote exec has warning.\n");
    }
    elsif ( $sshExec->{status} eq 'ERROR' ) {
        $hasError = $hasError + 1;
        print("ERROR: ssh remote exec has error.\n");
    }

    return $hasError;
}

exit main();

