#!/usr/bin/perl
use strict;
use FindBin;
use IO::File;
use Getopt::Long;
use File::Basename;

use AutoExecUtils;

sub usage {
    my $pname = $FindBin::Script;

    print("Usage: $pname [--verbose 0|1]\n");
    print("       --target:    Local mount path .\n");
    exit(1);
}

sub main {
    my ( $isHelp, $isVerbose );
    my ( $node,   $target );

    AutoExecUtils::setEnv();
    my $pname = $FindBin::Script;

    my $isVerbose = 0;

    GetOptions(
        'h|help'      => \$isHelp,
        'v|verbose=i' => \$isVerbose,
        'target=s'    => \$target
    );

    usage() if ( defined($isHelp) );

    my $optionError = 0;

    if ( not defined($target) or $target eq '' ) {
        print("ERROR: must define local mount path.\n");
        usage();
    }
    if ( $target =~ /\/\.\.\// or $target =~ /^\.\.\// or $target =~ /\/\.\.$/ ) {
        print("ERROR: dest path can not has parent dir opertor:\"..\".\n");
        $optionError = 1;
    }

    if ( $optionError == 1 ) {
        usage();
    }

    #umount -l /mnt/nas
    my $cmd = "umount";
    if ( $isVerbose == 1 ) {
        $cmd = $cmd . ' --verbose';
    }
    $cmd = $cmd . " $target";
    my $ret = `$cmd`;

    if ( $? == 0 ) {
        print("FINE: Umount $target success.\n");
    }
    else {
        print("ERROR: Umount $target failed.\n");
    }
    return $ret;
}

exit main();

