#!/usr/bin/env python3
# -*- coding:UTF-8 -*-

import argparse
import datetime
import time
import sys
import os
import AutoExecUtils

class Snowflake:
    def __init__(self, worker_id=1):
        self.worker_id = worker_id & 0x1F   # 支持 0~31
        self.sequence = 0
        self.last_ts = -1
        self.lock = threading.Lock()
        self.epoch = 1609459200000 

    def _time(self):
        return int(time.time() * 1000)

    def get_id(self):
        with self.lock:
            ts = self._time()
            if ts == self.last_ts:
                self.sequence = (self.sequence + 1) & 0xFFF 
            else:
                self.sequence = 0
            self.last_ts = ts
            sid = ((ts - self.epoch) << 22) | (self.worker_id << 12) | self.sequence
            return sid % (10 ** 16)

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--tag", default="", help="tag类型")
    args = parser.parse_args()

    tag = args.tag
    if tag is None or tag == "":
        tag = "timestamp"
    
    numberNo = None 
    if tag == "timestamp":
        now = datetime.datetime.now()
        numberNo = now.strftime("%Y%m%d%H%M%S")
    elif tag == "jobId":
        numberNo = os.getenv("AUTOEXEC_JOBID")
    elif tag == "snowflake":
        snowflake = Snowflake(worker_id=1)
        numberNo = snowflake.get_id()

    AutoExecUtils.saveOutput({"numberNo": numberNo})