#!/usr/bin/perl
use strict;
use FindBin;
use Cwd qw(abs_path);
use Getopt::Long;
use AutoExecUtils;
use Net::OpenSSH;
use JSON;

sub usage {
    my $pname = $FindBin::Script;
    print("$pname --node <node> --timeout <timeout seconds> .\n");
    exit(-1);
}

sub main {
    $| = 1;    #不对输出进行buffer，便于实时看到输出日志
    AutoExecUtils::setEnv();

    my ($node);

    my $timeout = 10;

    GetOptions(
        'node=s'    => \$node,
        'timeout=i' => \$timeout
    );

    my $nodeInfo  = {};
    my $hasOptErr = 0;
    if ( not defined($node) ) {
        $node = $ENV{AUTOEXEC_NODE};
    }

    if ( not defined($node) or $node eq '' ) {
        $hasOptErr = 1;
    }
    else {
        $nodeInfo = from_json($node);
    }

    if ( $hasOptErr == 1 ) {
        usage();
    }

    my $resourceId = $nodeInfo->{resourceId};
    my $host       = $nodeInfo->{host};
    my $port       = int( $nodeInfo->{port} );
    my $user       = $nodeInfo->{username};
    my $password   = $nodeInfo->{password};
    if ( $port == 0 or $port == 65535 ) {
        $port = int( $nodeInfo->{protocolPort} );
    }

    my $data = {
        MGMT_IP      => $host,
        PORT         => $port,
        RESOURCE_ID  => $resourceId,
        AVAILABILITY => 0
    };

    print("INFO: Try to ssh logon to $user\@$host:$port.\n");
    my $startTime = time();
    my $ssh       = Net::OpenSSH->new(
        $host,
        port        => $port,
        user        => $user,
        password    => $password,
        timeout     => 10,
        master_opts => [ -o => "StrictHostKeyChecking=no" ]
    );

    my $responseTime = time() - $startTime;
    $data->{RESPONSE_TIME} = $responseTime;

    if ( not $ssh->error ) {
        my $out = $ssh->capture("echo HEALTH_OK");
        if ( $out =~ /HEALTH_OK/ ) {
            $data->{AVAILABILITY}  = 1;
            $data->{ERROR_MESSAGE} = '';
        }
        print("FINE: SSH logon succeed.\n");
    }
    else {
        $data->{ERROR_MESSAGE} = $ssh->error;
        $data->{AVAILABILITY}  = 0;
        print( "WARN: ", $ssh->error, "\n" );
    }

    my $out = {};
    $out->{DATA} = $data;
    AutoExecUtils::saveOutput($out);
    print Dumper ($data);

    return 0;
}

exit main();
