#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
import json
import os
import sys
import time
import copy

from pathlib import Path

import AutoExecUtils
import ServerAdapter


binPaths = os.path.split(os.path.realpath(__file__))
libPath = os.path.realpath(binPaths[0] + "/../lib")
sys.path.append(libPath)


# 这个类确保传递给程序的所有参数都是偶数对的。如果参数的数目不是偶数，它会抛出一个错误。
class EvenPairsAction(argparse.Action):
    def __call__(self, parser, namespace, values, option_string=None):
        if len(values) % 2 != 0:
            raise argparse.ArgumentTypeError("The number of arguments must be even.")
        setattr(namespace, self.dest, values)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    # parser.add_argument('--rerunStrategy', type=str,  help='重跑策略', required=False)
    parser.add_argument("--jobMode", type=str, help="作业模式", default="child",required=True)
    parser.add_argument("--combopName", type=str, help="组合工具名", required=True)
    parser.add_argument("--name", type=str, help="作业名", required=True)
    parser.add_argument("--scenarioName", type=str, default="", help="场景名", required=False)
    parser.add_argument("--source", type=str, default="combop", help="来源 itsm|combop ITSM|组合工具发起的等", required=False)
    parser.add_argument("--roundCount", type=int, default=3, help="轮次", required=False)
    parser.add_argument("--planStartTime", type=int, help="计划时间", required=False)
    parser.add_argument("--triggerType", type=str, default="", help="触发方式 auto,manual", required=False)
    parser.add_argument("--assignExecUser", type=str, default="", help="指定执行用户", required=False)
    parser.add_argument("--protocol", type=str, default="", help="执行目标，指定执行协议", required=False)
    parser.add_argument("--executeUser", type=str, default="", help="执行目标，指定执行用户", required=False)
    parser.add_argument("--inputNodeList", type=str, default="", help="执行目标，指定执行节点", required=False) 
    parser.add_argument('--runnerGroup', type=str, default="", help="执行器组", required=False)
    parser.add_argument('--runnerGroupTag', type=str, default="", help="执行器组标签", required=False)
    parser.add_argument("param", type=str, nargs="*", action=EvenPairsAction, help="执行参数")
    args = parser.parse_args()

    param = {}
    for i in range(0, len(args.param), 2):
        param[args.param[i]] = args.param[i + 1]
    
    runnerGroup = None 
    if ( args.runnerGroup is not  None and args.runnerGroup != '' ):
        runnerGroup = args.runnerGroup
    
    runnerGroupTag = None 
    if ( args.runnerGroupTag is not  None and args.runnerGroupTag != '' ):
        runnerGroupTag = args.runnerGroupTag

    # for key, value in os.environ.items():
    #     print(f"{key}={value}")
    data = {
        "combopName": args.combopName,
        "name": args.name,
        "source": args.source or "combop",
        "scenarioName": args.scenarioName,
        "triggerType": args.triggerType,
        "planStartTime": args.planStartTime,
        "roundCount": args.roundCount,
        "assignExecUser": args.assignExecUser or os.environ.get("USER"),
        "param": param,
        "invokeId": os.environ.get("AUTOEXEC_JOBID"),
    }

    if args.jobMode == "child" :
        data["parentId"]=os.environ.get("AUTOEXEC_JOBID")

    if runnerGroup is not None :
        data["runnerGroup"]=runnerGroup
    
    if runnerGroupTag is not None :
        data["runnerGroupTag"]=runnerGroupTag

    if args.protocol and args.executeUser and args.inputNodeList:
        data["executeConfig"] = {"protocol": args.protocol, "executeUser": {"mappingMode": "constant", "value": args.executeUser}, "executeNodeConfig": {"inputNodeList": json.loads(args.inputNodeList)}, "whenToSpecify": "runtime"}
    
    #原有的data数据在执行接口调用会往里面加一些内置参数，复制数据方便重跑比对
    nativeData = copy.deepcopy(data)
    context = AutoExecUtils.getAutoexecContext()
    serverAdapter = ServerAdapter.ServerAdapter(context)

    # 从环境变量中获取用户名（AUTOEXEC_USER）和密码（EXECUSER_TOKEN）
    user = None
    password = None
    if os.environ.get("PASSTHROUGH_ENV"):
        # 优先使用当前用户的token
        passThroughEnv = json.loads(os.environ.get("PASSTHROUGH_ENV"))
        if passThroughEnv.get("EXECUSER_TOKEN"):
            user = os.environ.get("AUTOEXEC_USER")
            password = passThroughEnv.get("EXECUSER_TOKEN")

    # 可能会与loop插件结合，此处情况可能是多个，调整为作业的参数完全一样才匹配是否重跑
    jobList = []
    jobIdList = []
    outputPath = os.getenv("NODE_OUTPUT_PATH")
    if os.path.exists(outputPath):
        prevData = AutoExecUtils.getOpPreOutput()
        isCreated = 0
        createdJobId = None
        if prevData is not None and prevData.get("data") is not None:
            jobList = prevData.get("data")
            for job in jobList:
                createdJobId = job.get("createdJobId")
                jobIdList.append("{}".format(createdJobId))
                param = job.get("param")
                if param == data :
                    isCreated = 1

        if isCreated == 1 :
            job_status = AutoExecUtils.getJobStatus({"jobId": createdJobId, "proxyToUrl": None})
            print("INFO:: Job already exists {}, job status :{}.".format(createdJobId, job_status))
            if job_status in ("aborted", "paused", "completed", "failed"):
                print("INFO:: Job already exists, refire job {}.".format(createdJobId))
                # 这个接口没有返回值
                serverAdapter.refireJob({"jobId": createdJobId, "type": "refireAll"}, user, password)
            exit(0)

    resp = serverAdapter.createJobFromCombop(data, user, password)
    if resp is not None:
        createdJobId = resp["jobId"]
        jobIdList.append("{}".format(createdJobId))
        print("INFO:: Create job success,jobId:{}.".format(createdJobId))
        jobList.append({"createdJobId": createdJobId,"param":nativeData})

        #考虑loop创建作业情况，如果是在loop内加上waitjob效率太低了,冗余参数支持在loop外统一waitjob 
        createdJobIds = ",".join(jobIdList)
        out={
            "data": jobList,
            "createdJobId": createdJobId,
            "createdJobIds": createdJobIds
        }
        AutoExecUtils.saveOutput(out)
        exit(0)
    else:
        print("ERROR:: Create job failed.")
        exit(1)
