#!/usr/bin/python
# -*- coding:UTF-8 -*-

import traceback
import argparse
import json

import AutoExecUtils

if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument('--nodes', default='', help='Nodes json')
    parser.add_argument('--hostname', default='', help='Host name prefix')
    args = parser.parse_args()
    hostNamePrefix = args.hostname
    nodesJson = args.nodes
    nodes = json.loads(nodesJson)

    out = {}
    hostIps = []
    for node in nodes:
        hostIp = node.get('host')

        if hostIp is not None and hostIp != '':
            hostIps.append(hostIp)

    hostCount = len(hostIps)
    idx = 1
    for hostIp in hostIps.sort():
        out[hostIp] = hostNamePrefix + idx
        idx = idx + 1

    AutoExecUtils.saveOutput(out)
