#!/usr/bin/perl
use FindBin;
use lib "$FindBin::Bin/lib/perl-lib/lib/perl5";
use lib "$FindBin::Bin/lib";

use strict;
use IO::File;
use File::Basename;
use Cwd 'abs_path';
use Getopt::Long;

Getopt::Long::Configure qw(gnu_getopt);
Getopt::Long::Configure("pass_through");

sub usage {
    my $pname = basename($0);

    print("Usage: $pname [--verbose 0|1] [--action ActionName] <wls options...>\n");
    print("       --action:      start|stop|deploy|undeploy|patch|unpatch..., see document\n");
    print("       wls options:   weblogic config options, see document\n");

    exit(1);
}

sub main {
    my ( $ishelp, $insName, $action, $isVerbose );

    my $pname = basename($0);

    $isVerbose = 0;

    my %opts = (
        action               => '',
        inspath              => '',
        verbose              => '',
        java_home            => '',
        wls_home             => '',
        domain_home          => '',
        pkgs_dir             => '',
        backup_dir           => '',
        backup_count         => '',
        start_timeout        => '',
        stop_timeout         => '',
        admin_url            => '',
        LANG                 => '',
        LC_ALL               => '',
        umask                => '',
        standalone           => '',
        need_deploy          => '',
        wls_user             => '',
        wls_pwd              => '',
        servername           => '',
        appname              => '',
        appfile              => '',
        'source-path'        => '',
        target               => '',
        'staging-mode'       => '',
        'checkurl'           => '',
        'max_logfiles'       => '',
        'max_logsize'        => '',
        'max_logdays'        => '',
        'custom_stdoutfiles' => '',
        'USER_MEM_ARGS'      => '',
        'JAVA_EXT_OPTS'      => ''
    );

    GetOptions(
        \%opts, qw(
            action=s
            verbose=i
            java_home=s
            wls_home=s
            domain_home=s
            pkgs_dir=s
            backup_dir=s
            backup_count=s
            start_timeout=s
            stop_timeout=s
            admin_url=s
            LANG=s
            LC_ALL=s
            umask=s
            standalone=s
            need_deploy=s
            wls_user=s
            wls_pwd=s
            servername=s
            appname=s
            appfile=s
            source-path=s
            target=s
            staging-mode=s
            checkurl=s
            max_logsize=s
            max_logdays=s
            max_logfiles=s
            custom_stdoutfiles=s
            USER_MEM_ARGS=s
            JAVA_EXT_OPTS=s
        )
    ) || exit(1);

    $insName   = $opts{servername};
    $isVerbose = $opts{verbose};
    $action    = $opts{action};

    my $optionError = 0;
    if ( not defined($action) or $action eq '' ) {
        print("ERROR: Must define action by option --action.\n");
        $optionError = 1;
    }
    if ( not defined($insName) or $insName eq '' ) {
        print("ERROR: Must define servername by option --servername.\n");
        $optionError = 1;
    }

    if ( $optionError != 0 ) {
        usage();
    }

    my $hasError = 0;

    if ( $opts{wls_home} eq '' or $opts{admin_url} eq '' ) {
        print("ERROR: wls_home and admin_url must to be defined.\n");
        $hasError = 1;
    }

    my $appname    = '';
    my $servername = '';
    foreach my $key ( keys(%opts) ) {
        if ( $key eq "appname" ) {
            $appname = $opts{$key};
        }
        if ( $key eq "servername" ) {
            $servername = $opts{$key};
        }
    }

    my $newLine    = "\n";
    my $iniContent = '[app]';
    $iniContent = $iniContent . $newLine;
    foreach my $key ( keys(%opts) ) {
        if ( $key eq "source-path" || $key eq "target" || $key eq "staging-mode" ) {
            $iniContent = $iniContent . "$appname.$key=$opts{$key}$newLine";
        }
        elsif ( $key eq "checkurl" ) {
            $iniContent = $iniContent . "$servername.$appname.$key=$opts{$key}$newLine";
        }
        else {
            $iniContent = $iniContent . "$key=$opts{$key}$newLine";
        }
    }

    $hasError = execAction( $insName, 'wls', $iniContent, $action, \@ARGV, $isVerbose );

    return $hasError;
}

sub execAction {
    my ( $insName, $runtimeBaseName, $iniContent, $action, $envArgs, $isVerbose ) = @_;

    my $hasError = 0;

    if ( $hasError eq 0 ) {
        my $envParams = '';
        if ( defined($envArgs) and scalar(@$envArgs) > 0 ) {
            $envParams = '"' . join( '" "', @$envArgs ) . '"';
        }

        my $confFH = IO::File->new(">conf/wls.ini");
        if ( not defined($confFH) ) {
            print("ERROR: Can not open file conf/was.ini to write, $!\n");
            exit(2);
        }
        else {
            print $confFH($iniContent);
            $confFH->close();
        }

        exec("perl bin/$runtimeBaseName-$action.pl app $insName $envParams");
    }

    return $hasError;
}

exit main();

