#!/usr/bin/perl
use strict;
use SwitchSnmp;

sub main {
    my $collector = SwitchSnmp->new( hostname => '192.168.0.252', community => 'public', timeout => 10 );
    $collector->addScalarOid( SN => '1.3.6.1.2.1.47.1.1.1.1.11.1' );

    my $data = $collector->collect();
    print Dumper ($data);
}

exit( main() );

