#!/usr/bin/perl
use FindBin;
use lib $FindBin::Bin;
use lib "$FindBin::Bin/lib";
use lib "$FindBin::Bin/../lib";
use lib "$FindBin::Bin/../plib/lib/perl5";

use strict;

use JSON;
use Getopt::Long;
use AutoExecUtils;
use CollectObjCat;
use FCSwitchBase;
use Data::Dumper;

sub usage {
    my $pname = $FindBin::Script;
    print("INFO: :option --node or --type not defined.\n");
    print("$pname --node <node> --type <type> --sshaccount <ssh account> --community <defalut snmp community> --inspect <0|1> --timeout <time out seconds>|.\n");
    exit(0);
}

sub main {
    $| = 1;    #不对输出进行buffer，便于实时看到输出日志
    AutoExecUtils::setEnv();

    my ( $node, $type );

    my $sshAccount;
    my $defaultCommunity;
    my $timeout   = 10;
    my $isVerbose = 0;
    my $inspect   = 0;

    GetOptions(
        'verbose=i'    => \$isVerbose,
        'node=s'       => \$node,
        'type=s'       => \$type,
        'sshaccount=s' => \$sshAccount,
        'community=s'  => \$defaultCommunity,
        'inspect=i'    => \$inspect,
        'timeout=i'    => \$timeout
    );

    my $nodeInfo  = {};
    my $hasOptErr = 0;
    if ( not defined($node) ) {
        $node = $ENV{AUTOEXEC_NODE};
    }

    if ( not defined($node) or $node eq '' ) {
        $hasOptErr = 1;
    }
    else {
        $nodeInfo = from_json($node);
    }

    if ( $hasOptErr == 1 ) {
        usage();
    }

    if ( not defined($timeout) ) {
        $timeout = 10;
    }

    my $sshAccountInfo = {};
    if ( defined($sshAccount) and $sshAccount ne '' ) {
        if ( $sshAccount =~ /^\s*(\d+)\s*:\s*(\w+)\/(.*?)\s*$/ ) {
            my $protocolPort = int($1);
            if ( $protocolPort == 0 ) {
                $protocolPort = 22;
            }
            $sshAccountInfo->{protocolPort} = $protocolPort;
            $sshAccountInfo->{username}     = $2;
            $sshAccountInfo->{password}     = $3;
        }
        elsif ( $sshAccount =~ /^\s*(\w+)\/(.*?)\s*$/ ) {
            $sshAccountInfo->{protocolPort} = 22;
            $sshAccountInfo->{username}     = $1;
            $sshAccountInfo->{password}     = $2;
        }
    }

    my $hostname     = $nodeInfo->{host};
    my $community    = $nodeInfo->{password};
    my $protocol     = $nodeInfo->{protocol};
    my $protocolPort = $nodeInfo->{protocolPort};

    #version (i.e. 'snmpv1', 'snmpv2c', or 'snmpv3')
    if ( not defined($protocol) or $protocol eq '' or $protocol eq 'snmp' ) {
        $protocol = 'snmpv2c';
    }

    if ( not defined($community) or $community eq '' ) {

        #如果执行节点给出的协议不是snmp或者没有给出密码，则使用默认密码选项给出的团体字
        $community = $defaultCommunity;
    }
    if ( not defined($community) or $community eq '' ) {
        $community = 'public';
    }

    my $usmData  = {};
    my $authData = $nodeInfo->{authData};
    if ( defined($authData) ) {

        #snmpv3
        $usmData->{version}      = 'snmpv3';
        $usmData->{username}     = $authData->{username};
        $usmData->{authpassword} = $authData->{authPassword};
        $usmData->{authprotocol} = $authData->{authProtocol};
        $usmData->{privpassword} = $authData->{privPassword};
        $usmData->{privprotocol} = $authData->{privProtocol};

        if ( not defined( $usmData->{username} ) ) {
            $usmData->{username} = $nodeInfo->{username};
        }
        if ( not defined( $usmData->{authpassword} ) ) {
            $usmData->{authpassword} = $community;
        }
    }
    else {
        #snmpv2
        $usmData->{version}   = $protocol;
        $usmData->{community} = $community;
    }

    my $isFailed = 0;

    my $brand        = $type;
    my $fcswitchBase = FCSwitchBase->new( hostname => $hostname, port => $protocolPort, sshAccount => $sshAccountInfo, timeout => $timeout, node => $nodeInfo, %$usmData );
    if ( not defined($type) or $type eq '' or $type eq 'auto' ) {
        $brand = $fcswitchBase->getBrand();
    }

    if ( not defined($brand) or $brand eq '' ) {
        $isFailed = 1;
        print("ERROR: Can not discover the fcswitch device brand.\n");
    }
    else {
        print("INFO: FCSwitch brand: $brand.\n");
    }

    my $fcswitchIns;
    my $fcswitchClass = "FCSwitch$brand";
    if ( -e "$FindBin::Bin/$fcswitchClass.pm" or -e "$FindBin::Bin/lib/$fcswitchClass.pm" ) {
        print("INFO: Has defined class $fcswitchClass, try to load it.\n");
        eval {
            require "$fcswitchClass.pm";
            $fcswitchIns = $fcswitchClass->new( hostname => $hostname, community => $community, sshAccount => $sshAccountInfo, timeout => $timeout, node => $nodeInfo, inspect => $inspect );
        };
        if ($@) {
            $isFailed = 1;
            print("WARN: Load $fcswitchClass failed, $@");
            print("WARN: Fall back to FCSwitchBase class.\n");
            $fcswitchIns = $fcswitchBase;
        }
        else {
            print("INFO: Class $fcswitchClass loaded.\n");
        }
    }
    else {
        print("INFO: $fcswitchClass not found.\n");
        print("INFO: Fall back to FCSwitchBase class.\n");
        $fcswitchIns = $fcswitchBase;
    }

    my $data = $fcswitchIns->collect();
    $data->{BRAND} = $brand;
    if ( not defined( $data->{VENDOR} ) ) {
        $data->{VENDOR} = $data->{BRAND};
    }

    my $objCat = CollectObjCat->get('FCSWITCH');
    $data->{_OBJ_CATEGORY} = $objCat;
    $data->{_OBJ_TYPE}     = 'FCSwitch';
    $data->{_APP_TYPE}     = $brand;
    $data->{MGMT_IP}       = $nodeInfo->{host};
    $data->{PK}            = CollectObjCat->getPK($objCat);
    $data->{RESOURCE_ID}   = $nodeInfo->{resourceId};

    my $out = {};
    $out->{DATA} = [$data];
    AutoExecUtils::saveOutput($out);
    if ( $isVerbose == 1 ) {
        print("==================\n");
        print( to_json( $data, { pretty => 1 } ) );
        print("==================\n");
    }

    return $isFailed;
}

exit main();
