#!/usr/bin/perl
use Cwd qw(abs_path);
use FindBin;
use lib abs_path("$FindBin::Bin/lib");
use lib abs_path("$FindBin::Bin/../lib");

use strict;
use JSON;
use Getopt::Long;
use AutoExecUtils;
use SwitchSnmp;

#README
#如果新增其他品牌交换机，OID设置有问题，可能需要修改SwitchSnmp.pm, 修改开头的$BRANDS的定义，增加品牌名。
#参考：SwitchHuaWei.pm
#从SwitchBase.pm继承重载before方法调整snmp oid的设置
#重载after方法，进行数据的调整或者通过其他途径补充数据

sub main {
    $| = 1;    #不对输出进行buffer，便于实时看到输出日志
    AutoExecUtils::setEnv();

    my ( $node, $defaultCommunity, $timeout );

    GetOptions(
        'node=s'      => \$node,
        'community=s' => \$defaultCommunity,
        'timeout=i'   => \$timeout
    );

    my $hasOptErr = 0;
    if ( not defined($node) or $node eq '' ) {
        print("ERROR: option --node not defined.\n");
        $hasOptErr = 1;
    }
    else {
        $node = from_json($node);
    }

    if ( not defined($timeout) ) {
        $timeout = 10;
    }

    my $hostname  = $node->{host};
    my $community = $node->{password};
    if ( not defined($community) or $community eq '' ) {
        $community = $defaultCommunity;
    }
    if ( not defined($community) or $community eq '' ) {
        $community = 'public';
    }

    my $collector = SwitchSnmp->new( hostname => $node->{host}, community => $community, timeout => $timeout );
    my $data = $collector->collect();
    $data->{RESOURCE_ID} = $node->{resourceId};
    
    my $out = {};
    $out->{DATA} = $data;
    AutoExecUtils::saveOutput($out);
    print Dumper ($data);
}

main();
