#!/usr/bin/perl
use Cwd qw(abs_path);
use FindBin;
use lib abs_path($FindBin::Bin);
use lib abs_path("$FindBin::Bin/lib");
use lib abs_path("$FindBin::Bin/../lib");
use lib abs_path("$FindBin::Bin/../lib/perl-lib/lib/perl5");

use strict;
use JSON;
use Getopt::Long;
use AutoExecUtils;
use CollectObjCat;
use SwitchSnmp;

#README
#如果新增其他品牌交换机，OID设置有问题，可能需要修改SwitchSnmp.pm, 修改开头的$BRANDS的定义，增加品牌名。
#参考：SwitchHuaWei.pm
#从SwitchBase.pm继承重载before方法调整snmp oid的设置
#重载after方法，进行数据的调整或者通过其他途径补充数据
#测试：switchcollector --node '{"host":"192.168.0.252","password":"public"}'
sub main {
    $| = 1;    #不对输出进行buffer，便于实时看到输出日志
    AutoExecUtils::setEnv();

    my ( $node, $objType, $defaultCommunity, $timeout );

    my $isVerbose = 0;

    GetOptions(
        'verbose=i'   => \$isVerbose,
        'node=s'      => \$node,
        'community=s' => \$defaultCommunity,
        'objtype=s'   => \$objType,
        'timeout=i'   => \$timeout
    );

    my $hasOptErr = 0;
    if ( not defined($node) or $node eq '' ) {
        print("ERROR: option --node not defined.\n");
        $hasOptErr = 1;
    }
    else {
        $node = from_json($node);
    }

    if ( not defined($timeout) ) {
        $timeout = 10;
    }

    my $hostname  = $node->{host};
    my $community = $node->{password};
    if ( not defined($community) or $community eq '' ) {
        $community = $defaultCommunity;
    }
    if ( not defined($community) or $community eq '' ) {
        $community = 'public';
    }

    my $collector = SwitchSnmp->new( hostname => $hostname, community => $community, timeout => $timeout );
    my $data = $collector->collect();
    $data->{_OBJ_CATEGORY} = CollectObjCat->get('SWITCH');
    $data->{_OBJ_TYPE}     = $objType;
    $data->{PK}            = ['MGMT_IP'];
    $data->{RESOURCE_ID}   = $node->{resourceId};
    $data->{MGMT_IP}       = $hostname;

    my $out = {};
    $out->{DATA} = [$data];
    AutoExecUtils::saveOutput($out);
    if ( $isVerbose == 1 ) {
        print("==================\n");
        print( to_json( $data, { pretty => 1 } ) );
        print("==================\n");
    }

    return 0;
}

exit main();
